name: AppTemplate
fileGroups:
  - Configs/AppSecrets.xcconfig
options:
  bundleIdPrefix: com.boogios
  developmentLanguage: en
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: MAZQ6JDBT4
    CODE_SIGN_STYLE: Automatic
targets:
  AppTemplate:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    configFiles:
      Debug: Configs/AppSecrets.xcconfig
      Release: Configs/AppSecrets.xcconfig
    sources:
      - path: AppTemplate
    resources:
      - path: AppTemplate/Global/Assets.xcassets
      - path: AppTemplate/Global/Resource
      - path: AppTemplate/Global/Localizing
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boogios.template
        PRODUCT_NAME: AppTemplate
        INFOPLIST_FILE: AppTemplate/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
        DEVELOPMENT_ASSET_PATHS: "\"AppTemplate/Preview Content\""
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: GoogleUserMessagingPlatform
        product: GoogleUserMessagingPlatform
      - package: Mixpanel
        product: Mixpanel
  AppTemplateTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: AppTemplateTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boogios.templateTests
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AppTemplate
  AppTemplateUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: AppTemplateUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boogios.templateUITests
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: AppTemplate
    dependencies:
      - target: AppTemplate
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 13.0.0
  GoogleUserMessagingPlatform:
    url: https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git
    from: 3.1.0
  Mixpanel:
    url: https://github.com/mixpanel/mixpanel-swift
    from: 6.4.0
schemes:
  AppTemplate:
    build:
      targets:
        AppTemplate: all
        AppTemplateTests: [test]
        AppTemplateUITests: [test]
    test:
      config: Debug
      targets:
        - AppTemplateTests
        - AppTemplateUITests
    run:
      config: Debug
    archive:
      config: Release
